spring:
  application:
    name: restService

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect


  h2:
    console:
      enabled: true
server:
  port: 8080


logging:
  level:
    root: info
    com.msd.restservice: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/restservice.log
